export const DOC_AUTH_SUCCESS='DOC_AUTH_SUCCESS';
export const DOC_AUTH_FAIL='DOC_AUTH_FAIL';
export const DOC_AUTH_LOGOUT='DOC_AUTH_LOGOUT';
export const DOC_AUTH_REDIRECT='DOC_AUTH_REDIRECT';
export const DOC_SET_PROFILE='DOC_SET_PROFILE';
export const DOC_SET_PATIENTLIST='DOC_SET_PATIENTLIST';
export const DOC_GET_APPOINTMENT='DOC_GET_APPOINTMENT';
export const DOC_SET_NOTIFICATION='DOC_SET_NOTIFICATION';


export const PAT_AUTH_SUCCESS='PAT_AUTH_SUCCESS';
export const PAT_AUTH_FAIL='PAT_AUTH_FAIL';
export const PAT_AUTH_LOGOUT='PAT_AUTH_LOGOUT';
export const PAT_AUTH_REDIRECT='PAT_AUTH_REDIRECT';
export const PAT_SET_PROFILE='PAT_SET_PROFILE';
export const PAT_GET_DOCTORLIST='PAT_GET_DOCTORLIST';
export const PAT_GET_APPOINTMENT='PAT_GET_APPOINTMENT';
export const PAT_SET_NOTIFICATION='PAT_SET_NOTIFICATION';

